# Generated by Django 5.2 on 2025-12-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_ID', models.AutoField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=50)),
                ('L_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'other')], max_length=10)),
                ('Address', models.CharField(max_length=155)),
                ('Dob', models.DateField()),
                ('Contact_no', models.CharField(max_length=15)),
                ('Emp_type', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=30)),
                ('doj', models.DateField()),
                ('Designation', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Inactive')], max_length=20)),
            ],
        ),
    ]
