# Generated by Django 5.2 on 2026-01-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Emp_ID',
            new_name='Emp_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=15)),
                ('Manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=50)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.department')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_date', models.DateField()),
                ('Basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=15)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('InProgress', 'InProgress')], max_length=20)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField()),
                ('remark', models.CharField(max_length=255)),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='App.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='App.employee')),
            ],
        ),
    ]
