# Generated by Django 5.2 on 2026-01-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
