# Generated by Django 5.2 on 2026-01-25 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_employee_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Emp',
            new_name='Emp_id',
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('Present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('Total_days', models.IntegerField(default=0)),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='App.employee')),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('Total_days', models.IntegerField()),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='App.employee')),
            ],
        ),
        migrations.CreateModel(
            name='monthly_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mn_attendance', to='App.employee')),
            ],
        ),
        migrations.CreateModel(
            name='performance',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewd_date', models.DateField()),
                ('Attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='App.attendance')),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='App.employee')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp', to='App.employee')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='App.task')),
            ],
        ),
    ]
