# Generated by Django 5.2 on 2026-01-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_emp_task_emp_id_attendance_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(max_length=200),
        ),
    ]
