# Generated by Django 5.2 on 2026-01-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_attendance',
            name='date',
            field=models.DateField(verbose_name='%B'),
        ),
    ]
