# Generated by Django 5.2 on 2026-01-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_monthly_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
