# Generated by Django 5.2 on 2026-02-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_task_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('InProgress', 'InProgress')], default='Pending', max_length=20),
        ),
    ]
